package main;

import entity.Kakashi;
import entity.NPC_Boy;
import entity.NPC_Cat;
import entity.NPC_Dog;
import entity.NPC_Girl;
import entity.NPC_Man;
import entity.NPC_OldMan;
import entity.NPC_Oldwoman;
import entity.NPC_Woman;
import entity.Sakura;
import entity.Sasuke;
import entity.Tsunade;
import monster.GreenSlime;
import monster.Ninja;
import object.Boot;
import object.Door;
import object.Key;
import object.PotionRed;
import object.ShurikenObject;

public class AssetSetter {
    
    GamePanel gp;

    public AssetSetter(GamePanel g) {
        gp = g;
    }

    public void setObject() {

        int i = 0;

        gp.obj[i] = new Key(gp);
        gp.obj[i].worldX = gp.tileSize * 77;
        gp.obj[i].worldY = gp.tileSize * 23;
        i++;
        gp.obj[i] = new Door(gp);
        gp.obj[i].worldX = gp.tileSize * 82;
        gp.obj[i].worldY = gp.tileSize * 73;
        i++;
        gp.obj[i] = new PotionRed(gp);
        gp.obj[i].worldX = gp.tileSize * 66;
        gp.obj[i].worldY = gp.tileSize * 34;
        i++;
        gp.obj[i] = new ShurikenObject(gp);
        gp.obj[i].worldX = gp.tileSize * 72;
        gp.obj[i].worldY = gp.tileSize * 34;
        i++;
        gp.obj[i] = new Boot(gp);
        gp.obj[i].worldX = gp.tileSize * 68;
        gp.obj[i].worldY = gp.tileSize * 23;
        i++;

    }

    public void setNPC() {

        int i = 0;

        gp.npc[i] = new Tsunade(gp);
        gp.npc[i].worldX = gp.tileSize * 24;
        gp.npc[i].worldY = gp.tileSize * 9;
        i++;
        gp.npc[i] = new Kakashi(gp);
        gp.npc[i].worldX = gp.tileSize * 26;
        gp.npc[i].worldY = gp.tileSize * 70;
        i++;
        gp.npc[i] = new Sakura(gp);
        gp.npc[i].worldX = gp.tileSize * 26;
        gp.npc[i].worldY = gp.tileSize * 53;
        i++;
        gp.npc[i] = new NPC_OldMan(gp);
        gp.npc[i].worldX = gp.tileSize * 16;
        gp.npc[i].worldY = gp.tileSize * 63;
        i++;
        gp.npc[i] = new NPC_Dog(gp);
        gp.npc[i].worldX = gp.tileSize * 17;
        gp.npc[i].worldY = gp.tileSize * 60;
        i++;
        gp.npc[i] = new NPC_Dog(gp);
        gp.npc[i].worldX = gp.tileSize * 23;
        gp.npc[i].worldY = gp.tileSize * 40;
        i++;
        gp.npc[i] = new NPC_Dog(gp);
        gp.npc[i].worldX = gp.tileSize * 23;
        gp.npc[i].worldY = gp.tileSize * 36;
        i++;
        gp.npc[i] = new NPC_Cat(gp);
        gp.npc[i].worldX = gp.tileSize * 17;
        gp.npc[i].worldY = gp.tileSize * 59;
        i++;
        gp.npc[i] = new NPC_Cat(gp);
        gp.npc[i].worldX = gp.tileSize * 14;
        gp.npc[i].worldY = gp.tileSize * 36;
        i++;
        gp.npc[i] = new NPC_Cat(gp);
        gp.npc[i].worldX = gp.tileSize * 14;
        gp.npc[i].worldY = gp.tileSize * 45;
        i++;
        gp.npc[i] = new NPC_Cat(gp);
        gp.npc[i].worldX = gp.tileSize * 14;
        gp.npc[i].worldY = gp.tileSize * 50;
        i++;
        gp.npc[i] = new NPC_Woman(gp);
        gp.npc[i].worldX = gp.tileSize * 17;
        gp.npc[i].worldY = gp.tileSize * 52;
        i++;
        gp.npc[i] = new NPC_Woman(gp);
        gp.npc[i].worldX = gp.tileSize * 17;
        gp.npc[i].worldY = gp.tileSize * 51;
        i++;
        gp.npc[i] = new NPC_Oldwoman(gp);
        gp.npc[i].worldX = gp.tileSize * 14;
        gp.npc[i].worldY = gp.tileSize * 56;
        i++;
        gp.npc[i] = new NPC_Man(gp);
        gp.npc[i].worldX = gp.tileSize * 17;
        gp.npc[i].worldY = gp.tileSize * 48;
        i++;
        gp.npc[i] = new NPC_Oldwoman(gp);
        gp.npc[i].worldX = gp.tileSize * 17;
        gp.npc[i].worldY = gp.tileSize * 44;
        i++;
        gp.npc[i] = new NPC_OldMan(gp);
        gp.npc[i].worldX = gp.tileSize * 19;
        gp.npc[i].worldY = gp.tileSize * 40;
        i++;
        gp.npc[i] = new NPC_Oldwoman(gp);
        gp.npc[i].worldX = gp.tileSize * 17;
        gp.npc[i].worldY = gp.tileSize * 40;
        i++;
        gp.npc[i] = new NPC_Boy(gp);
        gp.npc[i].worldX = gp.tileSize * 15;
        gp.npc[i].worldY = gp.tileSize * 53;
        i++;
        gp.npc[i] = new NPC_Girl(gp);
        gp.npc[i].worldX = gp.tileSize * 17;
        gp.npc[i].worldY = gp.tileSize * 57;
        i++;
        gp.npc[i] = new NPC_Girl(gp);
        gp.npc[i].worldX = gp.tileSize * 19;
        gp.npc[i].worldY = gp.tileSize * 24;
        i++;
        gp.npc[i] = new NPC_Oldwoman(gp);
        gp.npc[i].worldX = gp.tileSize * 18;
        gp.npc[i].worldY = gp.tileSize * 24;
        i++;
        gp.npc[i] = new NPC_OldMan(gp);
        gp.npc[i].worldX = gp.tileSize * 19;
        gp.npc[i].worldY = gp.tileSize * 20;
        i++;
        gp.npc[i] = new NPC_Woman(gp);
        gp.npc[i].worldX = gp.tileSize * 17;
        gp.npc[i].worldY = gp.tileSize * 20;
        i++;
        gp.npc[i] = new NPC_Man(gp);
        gp.npc[i].worldX = gp.tileSize * 17;
        gp.npc[i].worldY = gp.tileSize * 19;
        i++;
        gp.npc[i] = new NPC_Girl(gp);
        gp.npc[i].worldX = gp.tileSize * 17;
        gp.npc[i].worldY = gp.tileSize * 28;
        i++;
        gp.npc[i] = new NPC_Oldwoman(gp);
        gp.npc[i].worldX = gp.tileSize * 18;
        gp.npc[i].worldY = gp.tileSize * 28;
        i++;
        gp.npc[i] = new NPC_OldMan(gp);
        gp.npc[i].worldX = gp.tileSize * 19;
        gp.npc[i].worldY = gp.tileSize * 28;
        i++;
        gp.npc[i] = new NPC_OldMan(gp);
        gp.npc[i].worldX = gp.tileSize * 19;
        gp.npc[i].worldY = gp.tileSize * 32;
        i++;
        gp.npc[i] = new NPC_Man(gp);
        gp.npc[i].worldX = gp.tileSize * 16;
        gp.npc[i].worldY = gp.tileSize * 32;
        i++;
        gp.npc[i] = new NPC_Girl(gp);
        gp.npc[i].worldX = gp.tileSize * 18;
        gp.npc[i].worldY = gp.tileSize * 32;
        i++;
        gp.npc[i] = new NPC_Oldwoman(gp);
        gp.npc[i].worldX = gp.tileSize * 19;
        gp.npc[i].worldY = gp.tileSize * 32;
        i++;
        gp.npc[i] = new NPC_OldMan(gp);
        gp.npc[i].worldX = gp.tileSize * 23;
        gp.npc[i].worldY = gp.tileSize * 32;
        i++;
        gp.npc[i] = new NPC_OldMan(gp);
        gp.npc[i].worldX = gp.tileSize * 17;
        gp.npc[i].worldY = gp.tileSize * 36;
        i++;
        gp.npc[i] = new NPC_OldMan(gp);
        gp.npc[i].worldX = gp.tileSize * 20;
        gp.npc[i].worldY = gp.tileSize * 36;
        i++;
        gp.npc[i] = new NPC_Oldwoman(gp);
        gp.npc[i].worldX = gp.tileSize * 19;
        gp.npc[i].worldY = gp.tileSize * 36;

        i++;
        gp.npc[i] = new NPC_Oldwoman(gp);
        gp.npc[i].worldX = gp.tileSize * 28;
        gp.npc[i].worldY = gp.tileSize * 50;
        i++;
        gp.npc[i] = new NPC_OldMan(gp);
        gp.npc[i].worldX = gp.tileSize * 30;
        gp.npc[i].worldY = gp.tileSize * 55;
        i++;
        gp.npc[i] = new NPC_OldMan(gp);
        gp.npc[i].worldX = gp.tileSize * 25;
        gp.npc[i].worldY = gp.tileSize * 60;
        i++;
        gp.npc[i] = new NPC_OldMan(gp);
        gp.npc[i].worldX = gp.tileSize * 25;
        gp.npc[i].worldY = gp.tileSize * 55;
        i++;
        gp.npc[i] = new NPC_Oldwoman(gp);
        gp.npc[i].worldX = gp.tileSize * 27;
        gp.npc[i].worldY = gp.tileSize * 56;

        i++;
        gp.npc[i] = new NPC_Girl(gp);
        gp.npc[i].worldX = gp.tileSize * 18;
        gp.npc[i].worldY = gp.tileSize * 66;
        i++;
        gp.npc[i] = new NPC_Oldwoman(gp);
        gp.npc[i].worldX = gp.tileSize * 28;
        gp.npc[i].worldY = gp.tileSize * 66;
        i++;
        gp.npc[i] = new NPC_OldMan(gp);
        gp.npc[i].worldX = gp.tileSize * 28;
        gp.npc[i].worldY = gp.tileSize * 62;
        i++;
        gp.npc[i] = new NPC_Woman(gp);
        gp.npc[i].worldX = gp.tileSize * 23;
        gp.npc[i].worldY = gp.tileSize * 59;
        i++;
        gp.npc[i] = new NPC_Man(gp);
        gp.npc[i].worldX = gp.tileSize * 27;
        gp.npc[i].worldY = gp.tileSize * 54;
        i++;
        gp.npc[i] = new NPC_Girl(gp);
        gp.npc[i].worldX = gp.tileSize * 23;
        gp.npc[i].worldY = gp.tileSize * 47;
        i++;
        gp.npc[i] = new NPC_Oldwoman(gp);
        gp.npc[i].worldX = gp.tileSize * 25;
        gp.npc[i].worldY = gp.tileSize * 40;

    }

    public void setMonster() {

        int i = 0;

        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 51;
        gp.monster[i].worldY = gp.tileSize * 87;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 51;
        gp.monster[i].worldY = gp.tileSize * 85;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 54;
        gp.monster[i].worldY = gp.tileSize * 24;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 54;
        gp.monster[i].worldY = gp.tileSize * 80;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 53;
        gp.monster[i].worldY = gp.tileSize * 76;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 55;
        gp.monster[i].worldY = gp.tileSize * 82;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 52;
        gp.monster[i].worldY = gp.tileSize * 24;
        


        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 51;
        gp.monster[i].worldY = gp.tileSize * 65;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 55;
        gp.monster[i].worldY = gp.tileSize * 69;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 54;
        gp.monster[i].worldY = gp.tileSize * 47;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 53;
        gp.monster[i].worldY = gp.tileSize * 56;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 55;
        gp.monster[i].worldY = gp.tileSize * 25;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 52;
        gp.monster[i].worldY = gp.tileSize * 35;


        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 51;
        gp.monster[i].worldY = gp.tileSize * 65;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 55;
        gp.monster[i].worldY = gp.tileSize * 24;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 54;
        gp.monster[i].worldY = gp.tileSize * 47;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 53;
        gp.monster[i].worldY = gp.tileSize * 56;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 55;
        gp.monster[i].worldY = gp.tileSize * 22;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 52;
        gp.monster[i].worldY = gp.tileSize * 32;


        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 51;
        gp.monster[i].worldY = gp.tileSize * 70;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 55;
        gp.monster[i].worldY = gp.tileSize * 47;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 54;
        gp.monster[i].worldY = gp.tileSize * 82;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 53;
        gp.monster[i].worldY = gp.tileSize * 67;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 55;
        gp.monster[i].worldY = gp.tileSize * 22;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 52;
        gp.monster[i].worldY = gp.tileSize * 54;

        //box1
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 65;
        gp.monster[i].worldY = gp.tileSize * 18;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 65;
        gp.monster[i].worldY = gp.tileSize * 20;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 66;
        gp.monster[i].worldY = gp.tileSize * 21;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 62;
        gp.monster[i].worldY = gp.tileSize * 21;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 63;
        gp.monster[i].worldY = gp.tileSize * 19;
        i++;
        
        //box2
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 75;
        gp.monster[i].worldY = gp.tileSize * 18;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 75;
        gp.monster[i].worldY = gp.tileSize * 20;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 76;
        gp.monster[i].worldY = gp.tileSize * 21;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 72;
        gp.monster[i].worldY = gp.tileSize * 21;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 73;
        gp.monster[i].worldY = gp.tileSize * 19;
        i++;

        //box3 & 4
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 75;
        gp.monster[i].worldY = gp.tileSize * 28;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 75;
        gp.monster[i].worldY = gp.tileSize * 30;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 76;
        gp.monster[i].worldY = gp.tileSize * 31;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 72;
        gp.monster[i].worldY = gp.tileSize * 31;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 73;
        gp.monster[i].worldY = gp.tileSize * 29;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 65;
        gp.monster[i].worldY = gp.tileSize * 28;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 65;
        gp.monster[i].worldY = gp.tileSize * 30;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 66;
        gp.monster[i].worldY = gp.tileSize * 31;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 62;
        gp.monster[i].worldY = gp.tileSize * 31;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 63;
        gp.monster[i].worldY = gp.tileSize * 29;
        i++;
        gp.monster[i] = new Ninja(gp);
        gp.monster[i].worldX = gp.tileSize * 72;
        gp.monster[i].worldY = gp.tileSize * 48;
        i++;
        gp.monster[i] = new Ninja(gp);
        gp.monster[i].worldX = gp.tileSize * 72;
        gp.monster[i].worldY = gp.tileSize * 46;
        i++;
        gp.monster[i] = new Ninja(gp);
        gp.monster[i].worldX = gp.tileSize * 72;
        gp.monster[i].worldY = gp.tileSize * 50;
        i++;
        gp.monster[i] = new Ninja(gp);
        gp.monster[i].worldX = gp.tileSize * 72;
        gp.monster[i].worldY = gp.tileSize * 44;
        i++;
        gp.monster[i] = new Ninja(gp);
        gp.monster[i].worldX = gp.tileSize * 72;
        gp.monster[i].worldY = gp.tileSize * 40;
        i++;
        gp.monster[i] = new Ninja(gp);
        gp.monster[i].worldX = gp.tileSize * 72;
        gp.monster[i].worldY = gp.tileSize * 38;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 65;
        gp.monster[i].worldY = gp.tileSize * 41;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 66;
        gp.monster[i].worldY = gp.tileSize * 43;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 73;
        gp.monster[i].worldY = gp.tileSize * 45;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 74;
        gp.monster[i].worldY = gp.tileSize * 49;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 69;
        gp.monster[i].worldY = gp.tileSize * 50;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 75;
        gp.monster[i].worldY = gp.tileSize * 48;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 69;
        gp.monster[i].worldY = gp.tileSize * 47;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 63;
        gp.monster[i].worldY = gp.tileSize * 29;
        i++;
        gp.monster[i] = new Ninja(gp);
        gp.monster[i].worldX = gp.tileSize * 72;
        gp.monster[i].worldY = gp.tileSize * 60;
        i++;
        gp.monster[i] = new Ninja(gp);
        gp.monster[i].worldX = gp.tileSize * 72;
        gp.monster[i].worldY = gp.tileSize * 63;
        i++;
        gp.monster[i] = new Ninja(gp);
        gp.monster[i].worldX = gp.tileSize * 72;
        gp.monster[i].worldY = gp.tileSize * 62;
        i++;
        gp.monster[i] = new Ninja(gp);
        gp.monster[i].worldX = gp.tileSize * 72;
        gp.monster[i].worldY = gp.tileSize * 57;
        i++;
        gp.monster[i] = new Ninja(gp);
        gp.monster[i].worldX = gp.tileSize * 72;
        gp.monster[i].worldY = gp.tileSize * 59;
        i++;
        gp.monster[i] = new Ninja(gp);
        gp.monster[i].worldX = gp.tileSize * 72;
        gp.monster[i].worldY = gp.tileSize * 61;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 69;
        gp.monster[i].worldY = gp.tileSize * 58;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 75;
        gp.monster[i].worldY = gp.tileSize * 58;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 69;
        gp.monster[i].worldY = gp.tileSize * 62;
        i++;
        gp.monster[i] = new GreenSlime(gp);
        gp.monster[i].worldX = gp.tileSize * 65;
        gp.monster[i].worldY = gp.tileSize * 60;

        //sasuke
        gp.monster[49] = new Sasuke(gp);
        gp.monster[49].worldX = gp.tileSize * 66;
        gp.monster[49].worldY = gp.tileSize * 76;
    }
}
